---
apiVersion: "v1"
kind: "Pod"
metadata:
  labels:
    jenkins: "agent"
    job/kind: "docker-image-build"
    docker-image/name: "${IMAGE_NAME}"
  annotations:
    container.apparmor.security.beta.kubernetes.io/builder: unconfined
    container.seccomp.security.alpha.kubernetes.io/builder: unconfined
spec:
  restartPolicy: "Never"
  containers:
    - name: builder
      image: jenkinsciinfra/builder:latest
      command:
        - cat
      tty: true
      resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "512Mi"
        cpu: "500m"
    - name: next-version
      image: gcr.io/jenkinsxio/jx-release-version:2.2.3
      command:
        - cat
      tty: true
      resources:
        limits:
          memory: "512Mi"
          cpu: "500m"
        requests:
          memory: "512Mi"
          cpu: "500m"
...
